### ISSUE TITLE
Remedy current limitations in denote-to-logseq migrator

### ISSUE THREAD

**Issue by hapst3r** [bitspook/notes-migrator#6]
As outlined in the README section, there are quite some "Known Limitations" in the current iteration of the denote-to-logseq migrator, and I intend to fix them sooner rather than later.

If I remember correctly, we had intended to open a new branch for this so that I can work on it without affecting the workings of the master branch, right?

#### TODO (prioritized)
- [x] **Links**. Currently, the description part of the link is lost.
- [ ] **Tags**. Logseq cannot parse Denote keywords.
- [ ] **Overwriting files**. There should be an error message or notification if one file or several files are about to be overwritten.
- [ ] **`LOGSEQ-DIRECTORY`**. There should be an error message if LOGSEQ-DIRECTORY is not set. If the directory specified does not exist, the user should be prompted if it shall be created.

**Comment by hapst3r** [comment]
I managed to fix the links, see commit e8b456e.

I initially wanted to use another branch, setting it up in emacs has not worked as expected, hence the push to master.

**EDIT**: Okay, I now managed to create a branch for the improvements I intend to make. Will continue to work on this branch until I am done with the TODOs. The branch is here [2-denote-logseq-improvements](https://github.com/bitspook/notes-migrator/tree/2-denote-logseq-improvements).

Again, if I am committing grave errurs, don't hesitate to tell me.
